//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFConsole.StoreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Storelib")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFConsole.StoreService.Product[] PersonsProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFConsole.StoreService.Product[] PersonsProducts {
            get {
                return this.PersonsProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonsProductsField, value) != true)) {
                    this.PersonsProductsField = value;
                    this.RaisePropertyChanged("PersonsProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Storelib")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvalibleProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvalibleProducts {
            get {
                return this.AvalibleProductsField;
            }
            set {
                if ((this.AvalibleProductsField.Equals(value) != true)) {
                    this.AvalibleProductsField = value;
                    this.RaisePropertyChanged("AvalibleProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((this.ProductPriceField.Equals(value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreService.IServiceStore")]
    public interface IServiceStore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/startup", ReplyAction="http://tempuri.org/IServiceStore/startupResponse")]
        string startup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/login", ReplyAction="http://tempuri.org/IServiceStore/loginResponse")]
        WPFConsole.StoreService.Person login(string nm, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/signup", ReplyAction="http://tempuri.org/IServiceStore/signupResponse")]
        string signup(string nm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/buyProduct", ReplyAction="http://tempuri.org/IServiceStore/buyProductResponse")]
        bool buyProduct(WPFConsole.StoreService.Product pt, int amount, WPFConsole.StoreService.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getAmountStore", ReplyAction="http://tempuri.org/IServiceStore/getAmountStoreResponse")]
        int getAmountStore(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getProduct", ReplyAction="http://tempuri.org/IServiceStore/getProductResponse")]
        WPFConsole.StoreService.Product getProduct(int productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getProductListStore", ReplyAction="http://tempuri.org/IServiceStore/getProductListStoreResponse")]
        WPFConsole.StoreService.Product[] getProductListStore();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getProductListPerson", ReplyAction="http://tempuri.org/IServiceStore/getProductListPersonResponse")]
        WPFConsole.StoreService.Product[] getProductListPerson(int personid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getSaldoPerson", ReplyAction="http://tempuri.org/IServiceStore/getSaldoPersonResponse")]
        int getSaldoPerson(int pid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStoreChannel : WPFConsole.StoreService.IServiceStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStoreClient : System.ServiceModel.ClientBase<WPFConsole.StoreService.IServiceStore>, WPFConsole.StoreService.IServiceStore {
        
        public ServiceStoreClient() {
        }
        
        public ServiceStoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string startup() {
            return base.Channel.startup();
        }
        
        public WPFConsole.StoreService.Person login(string nm, string pw) {
            return base.Channel.login(nm, pw);
        }
        
        public string signup(string nm) {
            return base.Channel.signup(nm);
        }
        
        public bool buyProduct(WPFConsole.StoreService.Product pt, int amount, WPFConsole.StoreService.Person p) {
            return base.Channel.buyProduct(pt, amount, p);
        }
        
        public int getAmountStore(int id) {
            return base.Channel.getAmountStore(id);
        }
        
        public WPFConsole.StoreService.Product getProduct(int productid) {
            return base.Channel.getProduct(productid);
        }
        
        public WPFConsole.StoreService.Product[] getProductListStore() {
            return base.Channel.getProductListStore();
        }
        
        public WPFConsole.StoreService.Product[] getProductListPerson(int personid) {
            return base.Channel.getProductListPerson(personid);
        }
        
        public int getSaldoPerson(int pid) {
            return base.Channel.getSaldoPerson(pid);
        }
    }
}
