//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testConsole.StoreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Storelib")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvalibleProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvalibleProducts {
            get {
                return this.AvalibleProductsField;
            }
            set {
                if ((this.AvalibleProductsField.Equals(value) != true)) {
                    this.AvalibleProductsField = value;
                    this.RaisePropertyChanged("AvalibleProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((this.ProductPriceField.Equals(value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Storelib")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private testConsole.StoreService.Product[] PersonsProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public testConsole.StoreService.Product[] PersonsProducts {
            get {
                return this.PersonsProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonsProductsField, value) != true)) {
                    this.PersonsProductsField = value;
                    this.RaisePropertyChanged("PersonsProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreService.IServiceStore")]
    public interface IServiceStore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/test", ReplyAction="http://tempuri.org/IServiceStore/testResponse")]
        string test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/startup", ReplyAction="http://tempuri.org/IServiceStore/startupResponse")]
        void startup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/login", ReplyAction="http://tempuri.org/IServiceStore/loginResponse")]
        bool login(string nm, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/signup", ReplyAction="http://tempuri.org/IServiceStore/signupResponse")]
        bool signup(string nm, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/setProductStore", ReplyAction="http://tempuri.org/IServiceStore/setProductStoreResponse")]
        void setProductStore(string nm, int pr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/setPerson", ReplyAction="http://tempuri.org/IServiceStore/setPersonResponse")]
        void setPerson(string nm, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getProductlistStore", ReplyAction="http://tempuri.org/IServiceStore/getProductlistStoreResponse")]
        testConsole.StoreService.Product[] getProductlistStore();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getProductlistPersoon", ReplyAction="http://tempuri.org/IServiceStore/getProductlistPersoonResponse")]
        testConsole.StoreService.Product[] getProductlistPersoon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getPerson", ReplyAction="http://tempuri.org/IServiceStore/getPersonResponse")]
        testConsole.StoreService.Person[] getPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/buyProduct", ReplyAction="http://tempuri.org/IServiceStore/buyProductResponse")]
        bool buyProduct(testConsole.StoreService.Product pt, int aantal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/searchProductPerson", ReplyAction="http://tempuri.org/IServiceStore/searchProductPersonResponse")]
        bool searchProductPerson(testConsole.StoreService.Product pt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getProductPerson", ReplyAction="http://tempuri.org/IServiceStore/getProductPersonResponse")]
        testConsole.StoreService.Product getProductPerson(testConsole.StoreService.Product pt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getProductStore", ReplyAction="http://tempuri.org/IServiceStore/getProductStoreResponse")]
        testConsole.StoreService.Product getProductStore(testConsole.StoreService.Product pt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/searchPerson", ReplyAction="http://tempuri.org/IServiceStore/searchPersonResponse")]
        bool searchPerson(string nm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/checkPassword", ReplyAction="http://tempuri.org/IServiceStore/checkPasswordResponse")]
        bool checkPassword(string nm, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getProductTestStore", ReplyAction="http://tempuri.org/IServiceStore/getProductTestStoreResponse")]
        testConsole.StoreService.Product getProductTestStore(string nm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStoreChannel : testConsole.StoreService.IServiceStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStoreClient : System.ServiceModel.ClientBase<testConsole.StoreService.IServiceStore>, testConsole.StoreService.IServiceStore {
        
        public ServiceStoreClient() {
        }
        
        public ServiceStoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string test() {
            return base.Channel.test();
        }
        
        public void startup() {
            base.Channel.startup();
        }
        
        public bool login(string nm, string pw) {
            return base.Channel.login(nm, pw);
        }
        
        public bool signup(string nm, string pw) {
            return base.Channel.signup(nm, pw);
        }
        
        public void setProductStore(string nm, int pr) {
            base.Channel.setProductStore(nm, pr);
        }
        
        public void setPerson(string nm, string pw) {
            base.Channel.setPerson(nm, pw);
        }
        
        public testConsole.StoreService.Product[] getProductlistStore() {
            return base.Channel.getProductlistStore();
        }
        
        public testConsole.StoreService.Product[] getProductlistPersoon() {
            return base.Channel.getProductlistPersoon();
        }
        
        public testConsole.StoreService.Person[] getPerson() {
            return base.Channel.getPerson();
        }
        
        public bool buyProduct(testConsole.StoreService.Product pt, int aantal) {
            return base.Channel.buyProduct(pt, aantal);
        }
        
        public bool searchProductPerson(testConsole.StoreService.Product pt) {
            return base.Channel.searchProductPerson(pt);
        }
        
        public testConsole.StoreService.Product getProductPerson(testConsole.StoreService.Product pt) {
            return base.Channel.getProductPerson(pt);
        }
        
        public testConsole.StoreService.Product getProductStore(testConsole.StoreService.Product pt) {
            return base.Channel.getProductStore(pt);
        }
        
        public bool searchPerson(string nm) {
            return base.Channel.searchPerson(nm);
        }
        
        public bool checkPassword(string nm, string pw) {
            return base.Channel.checkPassword(nm, pw);
        }
        
        public testConsole.StoreService.Product getProductTestStore(string nm) {
            return base.Channel.getProductTestStore(nm);
        }
    }
}
